"""create_initial_schema

Revision ID: c441566144e8
Revises:
Create Date: 2026-04-30 21:50:58.643019

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c441566144e8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "access_token",
            sa.Text(),
            nullable=False,
            comment="JWT access token used in Authorization: Bearer header. Valid for 4 hours.",
        ),
        sa.Column(
            "refresh_token",
            sa.Text(),
            nullable=False,
            comment="Token used to obtain a new access_token without re-authentication. Valid for 1 day.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when the access_token expires. Service rotates proactively when less than 30 minutes remain.",
        ),
        sa.Column(
            "refresh_expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when the refresh_token expires. If this is past, manual re-authentication is required.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_tokens")),
        comment="Stores the single active OAuth2 token for Tiny ERP API authentication. Always contains exactly one row. Updated on every token refresh cycle (every 2 hours proactively, or on 401 response).",
    )
    op.create_table(
        "orders",
        sa.Column(
            "tiny_id",
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
            comment="Unique order identifier in Tiny ERP. Primary key. Used for deduplication in upsert operations.",
        ),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=True),
        sa.Column("total_products_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_order_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_list", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "customer",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="JSONB with full customer data: name, tax_id (CPF/CNPJ), email, phone, address fields. Query with customer->>'name' syntax.",
        ),
        sa.Column("delivery_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ecommerce_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "ecommerce_name",
            sa.String(length=200),
            nullable=True,
            comment="Name of the e-commerce platform (e.g., 'Shopify', 'Mercado Livre'). NULL for direct sales. Used in sale_buckets for revenue attribution.",
        ),
        sa.Column("ecommerce_order_number", sa.String(length=100), nullable=True),
        sa.Column("channel_order_number", sa.String(length=100), nullable=True),
        sa.Column("sales_channel", sa.String(length=100), nullable=True),
        sa.Column(
            "carrier",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="JSONB with carrier info: name, shipping_method, tracking_code, tracking_url, freight_type.",
        ),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=True),
        sa.Column("warehouse_name", sa.String(length=200), nullable=True),
        sa.Column("seller", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("operation_nature", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("intermediary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "integrated_payments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "situation",
            sa.SmallInteger(),
            nullable=False,
            comment="Order status as integer. See table comment for value mapping. Use to filter active/completed/cancelled orders.",
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column("purchase_order_number", sa.String(length=100), nullable=True),
        sa.Column(
            "discount_value",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "shipping_value",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "other_expenses_value",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("shipping_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column("internal_observations", sa.Text(), nullable=True),
        sa.Column("order_origin", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("situation BETWEEN 0 AND 9", name=op.f("ck_orders_valid_situation")),
        sa.PrimaryKeyConstraint("tiny_id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
        comment="Mirror of all orders from Tiny ERP. Nested objects (customer, carrier, payment) are stored as JSONB to preserve the complete Tiny API structure. Order items are stored separately in order_items. The situation column uses Tiny's numeric codes: 0=Open, 1=Invoiced, 2=Cancelled, 3=Approved, 4=PreparingShipment, 5=Shipped, 6=Delivered, 7=ReadyToShip, 8=IncompleteData, 9=NotDelivered.",
    )
    op.create_index("ix_orders_ecommerce_id", "orders", ["ecommerce_id"], unique=False)
    op.create_index(
        "ix_orders_ecommerce_order_number", "orders", ["ecommerce_order_number"], unique=False
    )
    op.create_index("ix_orders_order_date", "orders", ["order_date"], unique=False)
    op.create_index("ix_orders_order_number", "orders", ["order_number"], unique=False)
    op.create_index("ix_orders_shipping_date", "orders", ["shipping_date"], unique=False)
    op.create_index("ix_orders_situation", "orders", ["situation"], unique=False)
    op.create_index("ix_orders_updated_at", "orders", ["updated_at"], unique=False)
    op.create_table(
        "products",
        sa.Column(
            "tiny_id",
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
            comment="Unique product identifier in Tiny ERP. Used as primary key. Never changes for a given product.",
        ),
        sa.Column(
            "sku",
            sa.String(length=100),
            nullable=False,
            comment="Stock Keeping Unit code. Unique identifier used in orders and stock management.",
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("complementary_description", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.String(length=1),
            nullable=False,
            comment="Product type: P=Physical Product, S=Service, K=Kit/Bundle. Kit products have components in product_kit_components table.",
        ),
        sa.Column(
            "situation",
            sa.String(length=1),
            nullable=False,
            comment="Product status in Tiny: A=Active (synced), I=Inactive, E=Deleted/Archived.",
        ),
        sa.Column("parent_product_tiny_id", sa.BigInteger(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("unit_per_box", sa.String(length=20), nullable=True),
        sa.Column("ncm", sa.String(length=20), nullable=True),
        sa.Column("gtin", sa.String(length=20), nullable=True),
        sa.Column("origin", sa.String(length=5), nullable=True),
        sa.Column("warranty", sa.String(length=100), nullable=True),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("category_name", sa.String(length=200), nullable=True),
        sa.Column("category_full_path", sa.String(length=500), nullable=True),
        sa.Column("brand_id", sa.BigInteger(), nullable=True),
        sa.Column("brand_name", sa.String(length=200), nullable=True),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "prices",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="JSONB with price, promotional_price, cost_price, average_cost_price as decimal numbers.",
        ),
        sa.Column("stock_control", sa.Boolean(), nullable=True),
        sa.Column("stock_on_order", sa.Boolean(), nullable=True),
        sa.Column("stock_preparation_days", sa.Integer(), nullable=True),
        sa.Column("stock_location", sa.String(length=200), nullable=True),
        sa.Column("stock_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("stock_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("stock_quantity", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "suppliers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=True,
        ),
        sa.Column("seo", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("taxation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "attachments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=True,
        ),
        sa.Column("variation_type", sa.String(length=5), nullable=True),
        sa.Column("created_at_tiny", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at_tiny", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last time this record was fetched from the Tiny API. Used to detect stale data.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "situation IN ('A', 'I', 'E')", name=op.f("ck_products_valid_situation")
        ),
        sa.CheckConstraint("type IN ('P', 'S', 'K')", name=op.f("ck_products_valid_type")),
        sa.ForeignKeyConstraint(
            ["parent_product_tiny_id"],
            ["products.tiny_id"],
            name=op.f("fk_products_parent_product_tiny_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("tiny_id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
        comment="Mirror of all products from Tiny ERP. Products of type K (kit) have their components stored in product_kit_components. The prices and dimensions columns use JSONB for flexibility as the Tiny API schema may evolve. The stock_quantity field is a snapshot from the listing API; authoritative stock data is in the stock table.",
    )
    op.create_index("ix_products_brand_name", "products", ["brand_name"], unique=False)
    op.create_index("ix_products_situation", "products", ["situation"], unique=False)
    op.create_index("ix_products_type", "products", ["type"], unique=False)
    op.create_index("ix_products_updated_at_tiny", "products", ["updated_at_tiny"], unique=False)
    op.create_table(
        "sale_buckets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bucket_date", sa.Date(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column(
            "ecommerce_name",
            sa.String(length=200),
            server_default=sa.text("'Direct'"),
            nullable=False,
            comment="Sales channel name. 'Direct' means the order had no ecommerce association. Used to attribute revenue to channels.",
        ),
        sa.Column(
            "quantity_sold",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "total_revenue",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("order_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "is_kit_expansion",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="When true, this bucket was generated by expanding a kit sale into its components. total_revenue is always 0 for expanded rows — revenue is only on the kit's direct bucket.",
        ),
        sa.Column(
            "source_kit_sku",
            sa.String(length=100),
            nullable=True,
            comment="Only populated when is_kit_expansion=true. Identifies which kit product generated this component quantity.",
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_buckets")),
        comment="Pre-computed daily sales aggregations per SKU and sales channel. Two types of rows: direct sales (is_kit_expansion=false, revenue populated) and kit expansion rows (is_kit_expansion=true, revenue=0). Kit expansion rows represent how many units of a component SKU were implicitly sold through kit sales. For example, if kit '10U-MAST' containing 10x 'MAST-FIT' was sold 2 times: direct bucket sku='10U-MAST' quantity=2 revenue=X, expansion bucket sku='MAST-FIT' quantity=20 revenue=0 source_kit_sku='10U-MAST'. Recomputed daily and after each order sync batch.",
    )
    op.create_index("ix_sale_buckets_bucket_date", "sale_buckets", ["bucket_date"], unique=False)
    op.create_index(
        "ix_sale_buckets_ecommerce_name", "sale_buckets", ["ecommerce_name"], unique=False
    )
    op.create_index("ix_sale_buckets_sku", "sale_buckets", ["sku"], unique=False)
    op.create_index(
        "ix_sale_buckets_sku_date", "sale_buckets", ["sku", "bucket_date"], unique=False
    )
    op.create_index(
        "uq_sale_buckets_natural_key",
        "sale_buckets",
        [
            "bucket_date",
            "sku",
            "ecommerce_name",
            "is_kit_expansion",
            sa.literal_column("COALESCE(source_kit_sku, '')"),
        ],
        unique=True,
    )
    op.create_table(
        "sync_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sync_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_processed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')", name=op.f("ck_sync_logs_valid_status")
        ),
        sa.CheckConstraint(
            "sync_type IN ('products', 'orders', 'stock', 'sale_buckets', 'token_rotation')",
            name=op.f("ck_sync_logs_valid_sync_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_logs")),
        comment="Audit log of all synchronization operations. Each sync job creates one row with status='running', then updates to 'completed' or 'failed'. The metadata column stores context-specific data like date ranges and page counts. Use this table to monitor sync health and diagnose failures.",
    )
    op.create_index("ix_sync_logs_started_at", "sync_logs", ["started_at"], unique=False)
    op.create_index("ix_sync_logs_status", "sync_logs", ["status"], unique=False)
    op.create_index("ix_sync_logs_sync_type", "sync_logs", ["sync_type"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_tiny_id", sa.BigInteger(), nullable=False),
        sa.Column("product_tiny_id", sa.BigInteger(), nullable=True),
        sa.Column("product_sku", sa.String(length=100), nullable=False),
        sa.Column("product_description", sa.Text(), nullable=True),
        sa.Column("product_type", sa.String(length=1), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("additional_info", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_tiny_id"],
            ["orders.tiny_id"],
            name=op.f("fk_order_items_order_tiny_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_tiny_id"],
            ["products.tiny_id"],
            name=op.f("fk_order_items_product_tiny_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        comment="Line items of each order. Each row is one product in one order. product_type K (kit) items should be expanded using product_kit_components for individual component counting. The product_tiny_id may be NULL if the product was not yet synced when the order was processed; always use product_sku as the reliable identifier.",
    )
    op.create_index("ix_order_items_order_tiny_id", "order_items", ["order_tiny_id"], unique=False)
    op.create_index("ix_order_items_product_sku", "order_items", ["product_sku"], unique=False)
    op.create_index(
        "ix_order_items_product_tiny_id", "order_items", ["product_tiny_id"], unique=False
    )
    op.create_table(
        "product_kit_components",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kit_product_tiny_id", sa.BigInteger(), nullable=False),
        sa.Column("component_product_tiny_id", sa.BigInteger(), nullable=True),
        sa.Column("component_sku", sa.String(length=100), nullable=False),
        sa.Column("component_description", sa.Text(), nullable=True),
        sa.Column("component_type", sa.String(length=1), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_product_tiny_id"],
            ["products.tiny_id"],
            name=op.f("fk_product_kit_components_component_product_tiny_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["kit_product_tiny_id"],
            ["products.tiny_id"],
            name=op.f("fk_product_kit_components_kit_product_tiny_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_kit_components")),
        sa.UniqueConstraint(
            "kit_product_tiny_id",
            "component_sku",
            name="uq_product_kit_components_kit_product_tiny_id_component_sku",
        ),
        comment="Components of kit/bundle products (type K). When a kit is sold, each component's quantity sold must be computed as kit_quantity * component_quantity. The component_product_tiny_id may be NULL if the component product has not been synced yet; component_sku is always populated and should be used for lookups.",
    )
    op.create_index(
        "ix_product_kit_components_component_product_tiny_id",
        "product_kit_components",
        ["component_product_tiny_id"],
        unique=False,
    )
    op.create_index(
        "ix_product_kit_components_component_sku",
        "product_kit_components",
        ["component_sku"],
        unique=False,
    )
    op.create_index(
        "ix_product_kit_components_kit_product_tiny_id",
        "product_kit_components",
        ["kit_product_tiny_id"],
        unique=False,
    )
    op.create_table(
        "stock",
        sa.Column("product_tiny_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("product_name", sa.Text(), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column(
            "balance",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "reserved",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "available",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_tiny_id"],
            ["products.tiny_id"],
            name=op.f("fk_stock_product_tiny_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_tiny_id", name=op.f("pk_stock")),
        sa.UniqueConstraint("sku", name=op.f("uq_stock_sku")),
        comment="Current stock levels for each product. The balance is the physical stock count, reserved is the quantity committed to open orders, and available = balance - reserved. Updated by webhooks (immediate) and by scheduled sync (hourly for products appearing in recent orders, daily full sync). Deposit-level breakdown is in stock_deposits.",
    )
    op.create_index(
        "ix_stock_available",
        "stock",
        ["available"],
        unique=False,
        postgresql_where=sa.text("available > 0"),
    )
    op.create_index("ix_stock_sku", "stock", ["sku"], unique=False)
    op.create_table(
        "stock_deposits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_tiny_id", sa.BigInteger(), nullable=False),
        sa.Column("deposit_tiny_id", sa.BigInteger(), nullable=False),
        sa.Column("deposit_name", sa.String(length=200), nullable=False),
        sa.Column("ignore", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "reserved",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "available",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_tiny_id"],
            ["stock.product_tiny_id"],
            name=op.f("fk_stock_deposits_product_tiny_id_stock"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_deposits")),
        sa.UniqueConstraint(
            "product_tiny_id",
            "deposit_tiny_id",
            name="uq_stock_deposits_product_tiny_id_deposit_tiny_id",
        ),
        comment="Stock levels broken down by physical deposit/warehouse. When ignore=true, this deposit should be excluded from available stock calculations. Updated atomically with the stock table — all deposits are replaced on each sync.",
    )
    op.create_index(
        "ix_stock_deposits_deposit_tiny_id", "stock_deposits", ["deposit_tiny_id"], unique=False
    )
    op.create_index(
        "ix_stock_deposits_product_tiny_id", "stock_deposits", ["product_tiny_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_deposits_product_tiny_id", table_name="stock_deposits")
    op.drop_index("ix_stock_deposits_deposit_tiny_id", table_name="stock_deposits")
    op.drop_table("stock_deposits")
    op.drop_index("ix_stock_sku", table_name="stock")
    op.drop_index(
        "ix_stock_available", table_name="stock", postgresql_where=sa.text("available > 0")
    )
    op.drop_table("stock")
    op.drop_index(
        "ix_product_kit_components_kit_product_tiny_id", table_name="product_kit_components"
    )
    op.drop_index("ix_product_kit_components_component_sku", table_name="product_kit_components")
    op.drop_index(
        "ix_product_kit_components_component_product_tiny_id", table_name="product_kit_components"
    )
    op.drop_table("product_kit_components")
    op.drop_index("ix_order_items_product_tiny_id", table_name="order_items")
    op.drop_index("ix_order_items_product_sku", table_name="order_items")
    op.drop_index("ix_order_items_order_tiny_id", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_sync_logs_sync_type", table_name="sync_logs")
    op.drop_index("ix_sync_logs_status", table_name="sync_logs")
    op.drop_index("ix_sync_logs_started_at", table_name="sync_logs")
    op.drop_table("sync_logs")
    op.drop_index("uq_sale_buckets_natural_key", table_name="sale_buckets")
    op.drop_index("ix_sale_buckets_sku_date", table_name="sale_buckets")
    op.drop_index("ix_sale_buckets_sku", table_name="sale_buckets")
    op.drop_index("ix_sale_buckets_ecommerce_name", table_name="sale_buckets")
    op.drop_index("ix_sale_buckets_bucket_date", table_name="sale_buckets")
    op.drop_table("sale_buckets")
    op.drop_index("ix_products_updated_at_tiny", table_name="products")
    op.drop_index("ix_products_type", table_name="products")
    op.drop_index("ix_products_situation", table_name="products")
    op.drop_index("ix_products_brand_name", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_orders_updated_at", table_name="orders")
    op.drop_index("ix_orders_situation", table_name="orders")
    op.drop_index("ix_orders_shipping_date", table_name="orders")
    op.drop_index("ix_orders_order_number", table_name="orders")
    op.drop_index("ix_orders_order_date", table_name="orders")
    op.drop_index("ix_orders_ecommerce_order_number", table_name="orders")
    op.drop_index("ix_orders_ecommerce_id", table_name="orders")
    op.drop_table("orders")
    op.drop_table("oauth_tokens")
    # ### end Alembic commands ###
