"""Unit tests for the executor's floor-violation guard.

This is the LAST line of defence before a price gets POSTed to ML.
The override path in the router already 422s anything below the
floor; this guard exists for everything else — rows generated by the
cron and never overridden, retries, future bulk-approve, etc. The
invariant the tests pin: the effective price a buyer would pay must
NEVER be below ``floor_price``, regardless of how we got here.

Without this guard, a row whose floor was None at generation (costs
absent) would leak through to ML even though we have no way to
verify margin safety.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

import pytest

from tiny_mirror.services.ml_promotion_service import MLPromotionService

pytestmark = pytest.mark.unit


@dataclass
class FakeRow:
    promo_type: str = "DEAL"
    list_price: Decimal | None = Decimal("100.00")
    floor_price: Decimal | None = Decimal("60.00")
    target_price: Decimal | None = Decimal("78.90")
    target_total_pct: Decimal | None = Decimal("21.10")


def test_target_above_floor_is_safe() -> None:
    # 78.90 > 60.00 → safe.
    assert MLPromotionService._floor_violation_reason(FakeRow()) is None


def test_target_at_floor_is_safe() -> None:
    # Exactly at the floor → safe. Tolerance is half a cent, so this
    # never trips on rounding.
    row = FakeRow(target_price=Decimal("60.00"))
    assert MLPromotionService._floor_violation_reason(row) is None


# 2026-06-05: o guard de piso do executor foi DESLIGADO (retorna sempre None).
# Na aprovação manual o operador decide (dupla confirmação no front p/ margem
# negativa); o CAP/piso só voltará na automação de aprovação. Os testes abaixo
# fixam o no-op pra documentar a mudança.
def test_target_below_floor_no_longer_blocks() -> None:
    row = FakeRow(target_price=Decimal("55.00"))
    assert MLPromotionService._floor_violation_reason(row) is None


def test_target_one_cent_below_floor_no_longer_blocks() -> None:
    row = FakeRow(target_price=Decimal("59.99"))
    assert MLPromotionService._floor_violation_reason(row) is None


def test_null_floor_no_longer_blocks_for_priced_promos() -> None:
    row = FakeRow(floor_price=None)
    assert MLPromotionService._floor_violation_reason(row) is None


def test_coupon_effective_above_floor_is_safe() -> None:
    # 30% off R$ 100 = R$ 70 effective; floor 60 → safe.
    row = FakeRow(
        promo_type="SELLER_COUPON_CAMPAIGN",
        target_price=None,
        target_total_pct=Decimal("30.00"),
    )
    assert MLPromotionService._floor_violation_reason(row) is None


def test_coupon_effective_below_floor_no_longer_blocks() -> None:
    row = FakeRow(
        promo_type="SELLER_COUPON_CAMPAIGN",
        target_price=None,
        target_total_pct=Decimal("50.00"),
    )
    assert MLPromotionService._floor_violation_reason(row) is None


def test_coupon_with_null_floor_no_longer_blocks() -> None:
    row = FakeRow(
        promo_type="SELLER_COUPON_CAMPAIGN",
        target_price=None,
        target_total_pct=Decimal("30.00"),
        floor_price=None,
    )
    assert MLPromotionService._floor_violation_reason(row) is None


def test_row_with_no_target_skips_floor_check() -> None:
    # If the body builder is going to return None anyway (no target,
    # not a coupon), the floor guard is irrelevant — the row will be
    # 'skipped' downstream. We return None here so the executor's
    # decision tree stays clean (skipped because body is None, not
    # because of a phantom floor violation).
    row = FakeRow(target_price=None, target_total_pct=None)
    assert MLPromotionService._floor_violation_reason(row) is None
